name: CI API
on:
  push:
    paths:
      - 'src/**'

  pull_request:
    paths:
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Poppler
        run: sudo apt-get update && sudo apt-get install poppler-utils

      - name: Begin CI
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3

      - name: Install dependencies
        run: npm i
        working-directory: ./

      - name: Run Jest Tests
        run: |
          npm run test
        working-directory: ./